# src/goose/components/__init__.py
from goose.registry import sys_registry

from .base import Component
from .buildins import (
    ApiParam,
    BatchComponent,
    BatchConfig,
    BreakComponent,
    CodeConfig,
    CodeRunner,
    ConditionBranch,
    ContinueComponent,
    EndComponent,
    EndConfig,
    HttpConfig,
    HttpRequester,
    Lambda,
    LambdaConfig,
    LLMComponent,
    LLMConfig,
    LoopComponent,
    LoopConfig,
    OutputComponent,
    OutputConfig,
    OutputDefinition,
    PluginComponent,
    PluginConfig,
    SelectorComponent,
    SelectorConfig,
    StartComponent,
    StartConfig,
)
from .protocol import ComponentDefinition,Port,UIConfig,ComponentMeta
from .registry import component_registry, register_component

sys_registry.register_domain("components", component_registry)

__all__ = [
    "Component",
    "register_component",
    "component_registry",
    "ApiParam",
    "BatchComponent",
    "BatchConfig",
    "BreakComponent",
    "CodeConfig",
    "CodeRunner",
    "ConditionBranch",
    "ContinueComponent",
    "EndComponent",
    "EndConfig",
    "HttpConfig",
    "HttpRequester",
    "LLMComponent",
    "LLMConfig",
    "Lambda",
    "LambdaConfig",
    "LoopComponent",
    "LoopConfig",
    "OutputComponent",
    "OutputConfig",
    "OutputDefinition",
    "PluginComponent",
    "PluginConfig",
    "SelectorComponent",
    "SelectorConfig",
    "StartComponent",
    "StartConfig",
    "ComponentDefinition",
    "Port",
    "UIConfig",
    "ComponentMeta",
]
